<h1 class="mb-3 text-center"><?= $pic['title'] ?></h1>
<section class="row">
    <div class="col-12">
        <img src="<?= $pic['src'] ?>" alt="<?= $pic['title'] ?>" class="img-fluid">
    </div>
    <div class="col-12 mt-3">
        <p><?= $pic['description'] ?></p>
    </div>
    <div class="col-6 mt-3 fst-italic font-weight-light">
        <p><?= $pic['updated_at'] ?></p>
    </div>
    <div class="col-6 mt-3 fst-italic font-weight-light">
        <p><?= $pic['author'] ?></p>
    </div>
</section>