<h1 class="text-center">Login</h1>
<?php if (!empty($error)) : ?>
    <div class="alert alert-danger" role="alert">
        <?= $error ?>
    </div>
<?php endif; ?>
<form method="POST">
<div class="mb-3">
  <label for="email" class="form-label">Email</label>
  <input type="text" class="form-control" id="email" name="email" placeholder="Email">
</div>
<div class="mb-3">
  <label for="password" class="form-label">Password</label>
  <input type="password" class="form-control" id="password" name="password" placeholder="Password">
</div>
<div class="mb-3">
  <input type="submit" class="btn btn-primary" name="submit" value="Login">
</div>
</form>