<h1>Upload</h1>
<?php if (!empty($errors)) : ?>
    <div class="alert alert-danger" role="alert">
        <?php foreach ($errors as $error) : ?>
            <p><?= $error ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if (isset($success)) : ?>
    <div class="alert alert-success" role="alert">
            <p>Le fichier a été uploadé avec succes !</p>
    </div>
<?php endif; ?>

<p>Attention ne pas uploader un fichier dont la taille est supérieure à <?= $upload_max_filesize ?> octets</p>
<form method="POST" enctype="multipart/form-data">
    <input type="file" name="image_file" accept="image/*">
    <input type="submit" name="upload" value="Upload">
</form>